version: 0.2
phases:
  install:
    commands:
      - echo Installing Windows Build Tools ...
      - npm install --global --production windows-build-tools
      - echo Installing Chunky CLI ...
      - npm install --global chunky-cli
  pre_build:
    commands:
      - echo Installing node dependencies ...
      - npm install
      - echo Preparing output environment
      - mkdir .chunky
      - mkdir .chunky/web
  build:
    commands:
      - echo Packaging the web app
      - npm run package:web
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: carmel-web-$(date +%Y-%m-%d)
