version: 0.2
phases:
  install:
    commands:
      - echo Using the right npm version
      - npm install --global npm@5.3.0
      - echo Installing Windows Build Tools ...
      - npm install --global --production windows-build-tools
      - echo Installing Chunky CLI ...
      - npm install --global chunky-cli
  pre_build:
    commands:
      - echo Installing node dependencies ...
      - npm install
  build:
    commands:
      - echo Packaging the desktop app
      - chunky package desktop
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  base-directory: '../chunky-desktop-build'
